name: Alphabetise & Geocode Hotels

on:
  push:
    branches:
      - main
    paths:
      - hotels.json

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install/verify Python deps
        run: |
          python3 -c "import json, requests" 2>/dev/null || pip install --break-system-packages requests

      - name: Alphabetise hotels
        run: python3 sort_hotels.py

      - name: Geocode hotels
        env:
          OPENCAGE_KEY: ${{ secrets.OPENCAGE_KEY }}
        run: python3 scripts/enrich.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add hotels.json hotels_geocoded.json
          git diff --cached --quiet || git commit -m "Auto alphabetise & geocode"
          git push
