name: Auto-Alphabetise
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sorter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Alphabetise hotels.json
        run: |
          python3 -c "
import json, re, pathlib
file=pathlib.Path('hotels.json')
data=json.loads(file.read_text(encoding='utf-8'))
data.sort(key=lambda h: re.sub(r'^(the|a|an)\s+','',h['Name'].strip(),flags=re.I).lower())
file.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
          "
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name  "GitHub Action"
          git add hotels.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Alphabetised hotels.json"
          git push
