name: Auto-Alphabetise Hotels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  alphasort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Alphabetise hotels.json
        run: |
          python3 - <<'PY'
import json, re, pathlib
path = pathlib.Path("hotels.json")
data = json.loads(path.read_text(encoding="utf-8"))

def sort_key(obj):
    return re.sub(r"^(the|a|an)\s+","",obj["Name"].strip(),flags=re.I).lower()

data.sort(key=sort_key)

path.write_text(
    json.dumps(data, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8"
)
PY

      - name: Commit changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name  "GitHub Action"
          git add hotels.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: alphabetise hotels.json" && git push)
