name: Alphabetise & Geocode Hotels

on:
  push:
    branches:
      - main
    paths:
      - hotels.json                 # only run when this file changes

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps (none actually needed)
        run: python3 -c "import json; import requests" || pip install requests

      - name: Alphabetise hotels
        run: python3 sort_hotels.py

      - name: Geocode hotels
        run: python3 scripts/enrich.py

      - name: Commit any new files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add hotels.json hotels_geocoded.json
          git diff --cached --quiet || git commit -m "Auto alphabetise & geocode"
          git push
