name: Alphabetise Hotels
on:
  push:
    branches:
      - main
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run sort_hotels.py and show confirmation
        run: python3 sort_hotels.py && echo "PYTHON SCRIPT RAN"

      - name: Set up git user for commit
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Commit and push if changed
        run: |
          git add hotels.json
          git diff --cached --quiet && echo "No changes to commit" || (git commit -m "Alphabetise hotels.json" && git push)
